//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenshotBoxPlugin.BoxNet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:boxnet", ConfigurationName="BoxNet.boxnetPort")]
    public interface boxnetPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_account_info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_account_info(out GreenshotBoxPlugin.BoxNet.SOAPUser user, string api_key, string auth_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string logout(string api_key, string auth_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_ticket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_ticket(out string ticket, string api_key);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_auth_token", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_auth_token(out string auth_token, out GreenshotBoxPlugin.BoxNet.SOAPUser user, string api_key, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#register_new_user", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string register_new_user(out string auth_token, out GreenshotBoxPlugin.BoxNet.SOAPUser user, string api_key, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_account_tree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_account_tree([System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] out byte[] tree, string api_key, string auth_token, long folder_id, string[] @params);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#export_tags", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string export_tags([System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] out byte[] tag_xml, string api_key, string auth_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#create_folder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string create_folder(out GreenshotBoxPlugin.BoxNet.SOAPFolder folder, string api_key, string auth_token, long parent_id, string name, long share);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#copy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string copy(out long new_id, string api_key, string auth_token, string target, long target_id, long destination_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#move", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string move(string api_key, string auth_token, string target, long target_id, long destination_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#rename", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string rename(string api_key, string auth_token, string target, long target_id, string new_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string delete(string api_key, string auth_token, string target, long target_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#public_share", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string public_share(out string public_name, string api_key, string auth_token, string target, long target_id, string password, string message, string[] emails);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#public_unshare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string public_unshare(string api_key, string auth_token, string target, long target_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#private_share", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string private_share(string api_key, string auth_token, string target, long target_id, string[] emails, string message, bool notify);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#add_to_mybox", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string add_to_mybox(string api_key, string auth_token, long file_id, string public_name, long folder_id, string tags);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#add_to_tag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string add_to_tag(string api_key, string auth_token, string[] tags, string target, long target_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#verify_registration_email", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string verify_registration_email(string api_key, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_file_info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_file_info(out GreenshotBoxPlugin.BoxNet.SOAPFileInfo info, string api_key, string auth_token, long file_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#set_description", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string set_description(string api_key, string auth_token, string target, long target_id, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_friends", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_friends([System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] out byte[] friends, string api_key, string auth_token, string[] @params);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#request_friends", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string request_friends(string api_key, string auth_token, string[] emails, string message, string[] @params);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#make_update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string make_update(string api_key, string auth_token, long folder_id, string[] file_ids, string update_type, string[] @params);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_updates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_updates([System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] out byte[] updates, string api_key, string auth_token, long begin_timestamp, long end_timestamp, string[] @params);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_versions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_versions(out SOAPVersion[] versions, string api_key, string auth_token, string target, long target_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#make_current_version", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string make_current_version(out SOAPVersion[] versions, string api_key, string auth_token, long version_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_collaborations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_collaborations(out SOAPCollaboration[] collaborations, string api_key, string auth_token, string target, long target_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#invite_collaborators", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string invite_collaborators(out string[] invited_collaborators, out string[] unsuccessful_invitations, out SOAPCollaboration[] collaborations, string api_key, string auth_token, string target, long target_id, string[] user_ids, string[] emails, string item_role_name, bool resend_invite, bool no_email, string[] @params);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#accept_collaboration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string accept_collaboration(out SOAPCollaboration[] collaborations, string api_key, string auth_token, long collaboration_id, bool accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#remove_collaboration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string remove_collaboration(out SOAPCollaboration[] collaborations, string api_key, string auth_token, long collaboration_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_collaboration_link", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_collaboration_link(out GreenshotBoxPlugin.BoxNet.SOAPCollaborationLink collaboration_links, string api_key, string auth_token, string target, long target_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#toggle_collaboration_link", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string toggle_collaboration_link(out GreenshotBoxPlugin.BoxNet.SOAPCollaborationLink collaboration_links, string api_key, string auth_token, string target, long target_id, bool enable);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_item_roles_for_item", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_item_roles_for_item(out SOAPItemRole[] item_roles, string api_key, string auth_token, string target, long target_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#collaboration_change_item_role", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string collaboration_change_item_role(out SOAPCollaboration[] collaborations, string api_key, string auth_token, long collaboration_id, string item_role_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#get_comments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string get_comments(out SOAPComment[] comments, string api_key, string auth_token, long target_id, string target);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#add_comment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string add_comment(out GreenshotBoxPlugin.BoxNet.SOAPComment comment, string api_key, string auth_token, long target_id, string target, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#delete_comment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string delete_comment(string api_key, string auth_token, long target_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string search(out SOAPSearchResultItem[] files, out SOAPSearchResultItem[] folders, string api_key, string auth_token, string query, int page, int per_page, string sort, string direction, string[] @params);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:boxnet#Box_SoapApi#toggle_folder_email", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPSearchResultItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPItemRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPCollaboration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SOAPVersion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string toggle_folder_email(out string upload_email, string api_key, string auth_token, long folder_id, bool enable);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string emailField;
        
        private int access_idField;
        
        private int user_idField;
        
        private long space_amountField;
        
        private long space_usedField;
        
        private long max_upload_sizeField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        public int access_id {
            get {
                return this.access_idField;
            }
            set {
                this.access_idField = value;
                this.RaisePropertyChanged("access_id");
            }
        }
        
        /// <remarks/>
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        public long space_amount {
            get {
                return this.space_amountField;
            }
            set {
                this.space_amountField = value;
                this.RaisePropertyChanged("space_amount");
            }
        }
        
        /// <remarks/>
        public long space_used {
            get {
                return this.space_usedField;
            }
            set {
                this.space_usedField = value;
                this.RaisePropertyChanged("space_used");
            }
        }
        
        /// <remarks/>
        public long max_upload_size {
            get {
                return this.max_upload_sizeField;
            }
            set {
                this.max_upload_sizeField = value;
                this.RaisePropertyChanged("max_upload_size");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPSearchMatchType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string collaboratorField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string search_textField;
        
        /// <remarks/>
        public string collaborator {
            get {
                return this.collaboratorField;
            }
            set {
                this.collaboratorField = value;
                this.RaisePropertyChanged("collaborator");
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public string search_text {
            get {
                return this.search_textField;
            }
            set {
                this.search_textField = value;
                this.RaisePropertyChanged("search_text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPSearchResultItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long idField;
        
        private string descriptionField;
        
        private string folder_pathField;
        
        private string thumbnailField;
        
        private string parent_idField;
        
        private SOAPSearchMatchType match_typeField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public string folder_path {
            get {
                return this.folder_pathField;
            }
            set {
                this.folder_pathField = value;
                this.RaisePropertyChanged("folder_path");
            }
        }
        
        /// <remarks/>
        public string thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
                this.RaisePropertyChanged("thumbnail");
            }
        }
        
        /// <remarks/>
        public string parent_id {
            get {
                return this.parent_idField;
            }
            set {
                this.parent_idField = value;
                this.RaisePropertyChanged("parent_id");
            }
        }
        
        /// <remarks/>
        public SOAPSearchMatchType match_type {
            get {
                return this.match_typeField;
            }
            set {
                this.match_typeField = value;
                this.RaisePropertyChanged("match_type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPComment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long comment_idField;
        
        private string messageField;
        
        private string user_nameField;
        
        private long user_idField;
        
        private long createdField;
        
        private string avatar_urlField;
        
        private SOAPComment[] reply_commentsField;
        
        /// <remarks/>
        public long comment_id {
            get {
                return this.comment_idField;
            }
            set {
                this.comment_idField = value;
                this.RaisePropertyChanged("comment_id");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                this.user_nameField = value;
                this.RaisePropertyChanged("user_name");
            }
        }
        
        /// <remarks/>
        public long user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        public long created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }
        
        /// <remarks/>
        public string avatar_url {
            get {
                return this.avatar_urlField;
            }
            set {
                this.avatar_urlField = value;
                this.RaisePropertyChanged("avatar_url");
            }
        }
        
        /// <remarks/>
        public SOAPComment[] reply_comments {
            get {
                return this.reply_commentsField;
            }
            set {
                this.reply_commentsField = value;
                this.RaisePropertyChanged("reply_comments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPItemRole : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string item_permissionsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public string item_permissions {
            get {
                return this.item_permissionsField;
            }
            set {
                this.item_permissionsField = value;
                this.RaisePropertyChanged("item_permissions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPCollaborationLink : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string role_nameField;
        
        private string urlField;
        
        /// <remarks/>
        public string role_name {
            get {
                return this.role_nameField;
            }
            set {
                this.role_nameField = value;
                this.RaisePropertyChanged("role_name");
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPCollaboration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string item_role_nameField;
        
        private string statusField;
        
        private string item_typeField;
        
        private long item_idField;
        
        private string item_nameField;
        
        private long item_user_idField;
        
        private string item_user_nameField;
        
        private long user_idField;
        
        private string nameField;
        
        private string emailField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string item_role_name {
            get {
                return this.item_role_nameField;
            }
            set {
                this.item_role_nameField = value;
                this.RaisePropertyChanged("item_role_name");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        public string item_type {
            get {
                return this.item_typeField;
            }
            set {
                this.item_typeField = value;
                this.RaisePropertyChanged("item_type");
            }
        }
        
        /// <remarks/>
        public long item_id {
            get {
                return this.item_idField;
            }
            set {
                this.item_idField = value;
                this.RaisePropertyChanged("item_id");
            }
        }
        
        /// <remarks/>
        public string item_name {
            get {
                return this.item_nameField;
            }
            set {
                this.item_nameField = value;
                this.RaisePropertyChanged("item_name");
            }
        }
        
        /// <remarks/>
        public long item_user_id {
            get {
                return this.item_user_idField;
            }
            set {
                this.item_user_idField = value;
                this.RaisePropertyChanged("item_user_id");
            }
        }
        
        /// <remarks/>
        public string item_user_name {
            get {
                return this.item_user_nameField;
            }
            set {
                this.item_user_nameField = value;
                this.RaisePropertyChanged("item_user_name");
            }
        }
        
        /// <remarks/>
        public long user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPVersion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long version_idField;
        
        private string authorField;
        
        private long updatedField;
        
        private long sizeField;
        
        private string sha1Field;
        
        /// <remarks/>
        public long version_id {
            get {
                return this.version_idField;
            }
            set {
                this.version_idField = value;
                this.RaisePropertyChanged("version_id");
            }
        }
        
        /// <remarks/>
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        public long updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        /// <remarks/>
        public long size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <remarks/>
        public string sha1 {
            get {
                return this.sha1Field;
            }
            set {
                this.sha1Field = value;
                this.RaisePropertyChanged("sha1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPFileInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long file_idField;
        
        private string file_nameField;
        
        private long folder_idField;
        
        private long sharedField;
        
        private string public_nameField;
        
        private long sizeField;
        
        private string descriptionField;
        
        private string sha1Field;
        
        private long createdField;
        
        private long updatedField;
        
        /// <remarks/>
        public long file_id {
            get {
                return this.file_idField;
            }
            set {
                this.file_idField = value;
                this.RaisePropertyChanged("file_id");
            }
        }
        
        /// <remarks/>
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                this.file_nameField = value;
                this.RaisePropertyChanged("file_name");
            }
        }
        
        /// <remarks/>
        public long folder_id {
            get {
                return this.folder_idField;
            }
            set {
                this.folder_idField = value;
                this.RaisePropertyChanged("folder_id");
            }
        }
        
        /// <remarks/>
        public long shared {
            get {
                return this.sharedField;
            }
            set {
                this.sharedField = value;
                this.RaisePropertyChanged("shared");
            }
        }
        
        /// <remarks/>
        public string public_name {
            get {
                return this.public_nameField;
            }
            set {
                this.public_nameField = value;
                this.RaisePropertyChanged("public_name");
            }
        }
        
        /// <remarks/>
        public long size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public string sha1 {
            get {
                return this.sha1Field;
            }
            set {
                this.sha1Field = value;
                this.RaisePropertyChanged("sha1");
            }
        }
        
        /// <remarks/>
        public long created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }
        
        /// <remarks/>
        public long updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:boxnet")]
    public partial class SOAPFolder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long folder_idField;
        
        private string folder_nameField;
        
        private long folder_type_idField;
        
        private int user_idField;
        
        private string pathField;
        
        private int sharedField;
        
        private string public_nameField;
        
        private string passwordField;
        
        private long parent_folder_idField;
        
        /// <remarks/>
        public long folder_id {
            get {
                return this.folder_idField;
            }
            set {
                this.folder_idField = value;
                this.RaisePropertyChanged("folder_id");
            }
        }
        
        /// <remarks/>
        public string folder_name {
            get {
                return this.folder_nameField;
            }
            set {
                this.folder_nameField = value;
                this.RaisePropertyChanged("folder_name");
            }
        }
        
        /// <remarks/>
        public long folder_type_id {
            get {
                return this.folder_type_idField;
            }
            set {
                this.folder_type_idField = value;
                this.RaisePropertyChanged("folder_type_id");
            }
        }
        
        /// <remarks/>
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("path");
            }
        }
        
        /// <remarks/>
        public int shared {
            get {
                return this.sharedField;
            }
            set {
                this.sharedField = value;
                this.RaisePropertyChanged("shared");
            }
        }
        
        /// <remarks/>
        public string public_name {
            get {
                return this.public_nameField;
            }
            set {
                this.public_nameField = value;
                this.RaisePropertyChanged("public_name");
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        public long parent_folder_id {
            get {
                return this.parent_folder_idField;
            }
            set {
                this.parent_folder_idField = value;
                this.RaisePropertyChanged("parent_folder_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface boxnetPortChannel : GreenshotBoxPlugin.BoxNet.boxnetPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class boxnetPortClient : System.ServiceModel.ClientBase<GreenshotBoxPlugin.BoxNet.boxnetPort>, GreenshotBoxPlugin.BoxNet.boxnetPort {
        
        public boxnetPortClient() {
        }
        
        public boxnetPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public boxnetPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public boxnetPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public boxnetPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string get_account_info(out GreenshotBoxPlugin.BoxNet.SOAPUser user, string api_key, string auth_token) {
            return base.Channel.get_account_info(out user, api_key, auth_token);
        }
        
        public string logout(string api_key, string auth_token) {
            return base.Channel.logout(api_key, auth_token);
        }
        
        public string get_ticket(out string ticket, string api_key) {
            return base.Channel.get_ticket(out ticket, api_key);
        }
        
        public string get_auth_token(out string auth_token, out GreenshotBoxPlugin.BoxNet.SOAPUser user, string api_key, string ticket) {
            return base.Channel.get_auth_token(out auth_token, out user, api_key, ticket);
        }
        
        public string register_new_user(out string auth_token, out GreenshotBoxPlugin.BoxNet.SOAPUser user, string api_key, string login, string password) {
            return base.Channel.register_new_user(out auth_token, out user, api_key, login, password);
        }
        
        public string get_account_tree(out byte[] tree, string api_key, string auth_token, long folder_id, string[] @params) {
            return base.Channel.get_account_tree(out tree, api_key, auth_token, folder_id, @params);
        }
        
        public string export_tags(out byte[] tag_xml, string api_key, string auth_token) {
            return base.Channel.export_tags(out tag_xml, api_key, auth_token);
        }
        
        public string create_folder(out GreenshotBoxPlugin.BoxNet.SOAPFolder folder, string api_key, string auth_token, long parent_id, string name, long share) {
            return base.Channel.create_folder(out folder, api_key, auth_token, parent_id, name, share);
        }
        
        public string copy(out long new_id, string api_key, string auth_token, string target, long target_id, long destination_id) {
            return base.Channel.copy(out new_id, api_key, auth_token, target, target_id, destination_id);
        }
        
        public string move(string api_key, string auth_token, string target, long target_id, long destination_id) {
            return base.Channel.move(api_key, auth_token, target, target_id, destination_id);
        }
        
        public string rename(string api_key, string auth_token, string target, long target_id, string new_name) {
            return base.Channel.rename(api_key, auth_token, target, target_id, new_name);
        }
        
        public string delete(string api_key, string auth_token, string target, long target_id) {
            return base.Channel.delete(api_key, auth_token, target, target_id);
        }
        
        public string public_share(out string public_name, string api_key, string auth_token, string target, long target_id, string password, string message, string[] emails) {
            return base.Channel.public_share(out public_name, api_key, auth_token, target, target_id, password, message, emails);
        }
        
        public string public_unshare(string api_key, string auth_token, string target, long target_id) {
            return base.Channel.public_unshare(api_key, auth_token, target, target_id);
        }
        
        public string private_share(string api_key, string auth_token, string target, long target_id, string[] emails, string message, bool notify) {
            return base.Channel.private_share(api_key, auth_token, target, target_id, emails, message, notify);
        }
        
        public string add_to_mybox(string api_key, string auth_token, long file_id, string public_name, long folder_id, string tags) {
            return base.Channel.add_to_mybox(api_key, auth_token, file_id, public_name, folder_id, tags);
        }
        
        public string add_to_tag(string api_key, string auth_token, string[] tags, string target, long target_id) {
            return base.Channel.add_to_tag(api_key, auth_token, tags, target, target_id);
        }
        
        public string verify_registration_email(string api_key, string login) {
            return base.Channel.verify_registration_email(api_key, login);
        }
        
        public string get_file_info(out GreenshotBoxPlugin.BoxNet.SOAPFileInfo info, string api_key, string auth_token, long file_id) {
            return base.Channel.get_file_info(out info, api_key, auth_token, file_id);
        }
        
        public string set_description(string api_key, string auth_token, string target, long target_id, string description) {
            return base.Channel.set_description(api_key, auth_token, target, target_id, description);
        }
        
        public string get_friends(out byte[] friends, string api_key, string auth_token, string[] @params) {
            return base.Channel.get_friends(out friends, api_key, auth_token, @params);
        }
        
        public string request_friends(string api_key, string auth_token, string[] emails, string message, string[] @params) {
            return base.Channel.request_friends(api_key, auth_token, emails, message, @params);
        }
        
        public string make_update(string api_key, string auth_token, long folder_id, string[] file_ids, string update_type, string[] @params) {
            return base.Channel.make_update(api_key, auth_token, folder_id, file_ids, update_type, @params);
        }
        
        public string get_updates(out byte[] updates, string api_key, string auth_token, long begin_timestamp, long end_timestamp, string[] @params) {
            return base.Channel.get_updates(out updates, api_key, auth_token, begin_timestamp, end_timestamp, @params);
        }
        
        public string get_versions(out SOAPVersion[] versions, string api_key, string auth_token, string target, long target_id) {
            return base.Channel.get_versions(out versions, api_key, auth_token, target, target_id);
        }
        
        public string make_current_version(out SOAPVersion[] versions, string api_key, string auth_token, long version_id) {
            return base.Channel.make_current_version(out versions, api_key, auth_token, version_id);
        }
        
        public string get_collaborations(out SOAPCollaboration[] collaborations, string api_key, string auth_token, string target, long target_id) {
            return base.Channel.get_collaborations(out collaborations, api_key, auth_token, target, target_id);
        }
        
        public string invite_collaborators(out string[] invited_collaborators, out string[] unsuccessful_invitations, out SOAPCollaboration[] collaborations, string api_key, string auth_token, string target, long target_id, string[] user_ids, string[] emails, string item_role_name, bool resend_invite, bool no_email, string[] @params) {
            return base.Channel.invite_collaborators(out invited_collaborators, out unsuccessful_invitations, out collaborations, api_key, auth_token, target, target_id, user_ids, emails, item_role_name, resend_invite, no_email, @params);
        }
        
        public string accept_collaboration(out SOAPCollaboration[] collaborations, string api_key, string auth_token, long collaboration_id, bool accept) {
            return base.Channel.accept_collaboration(out collaborations, api_key, auth_token, collaboration_id, accept);
        }
        
        public string remove_collaboration(out SOAPCollaboration[] collaborations, string api_key, string auth_token, long collaboration_id) {
            return base.Channel.remove_collaboration(out collaborations, api_key, auth_token, collaboration_id);
        }
        
        public string get_collaboration_link(out GreenshotBoxPlugin.BoxNet.SOAPCollaborationLink collaboration_links, string api_key, string auth_token, string target, long target_id) {
            return base.Channel.get_collaboration_link(out collaboration_links, api_key, auth_token, target, target_id);
        }
        
        public string toggle_collaboration_link(out GreenshotBoxPlugin.BoxNet.SOAPCollaborationLink collaboration_links, string api_key, string auth_token, string target, long target_id, bool enable) {
            return base.Channel.toggle_collaboration_link(out collaboration_links, api_key, auth_token, target, target_id, enable);
        }
        
        public string get_item_roles_for_item(out SOAPItemRole[] item_roles, string api_key, string auth_token, string target, long target_id) {
            return base.Channel.get_item_roles_for_item(out item_roles, api_key, auth_token, target, target_id);
        }
        
        public string collaboration_change_item_role(out SOAPCollaboration[] collaborations, string api_key, string auth_token, long collaboration_id, string item_role_name) {
            return base.Channel.collaboration_change_item_role(out collaborations, api_key, auth_token, collaboration_id, item_role_name);
        }
        
        public string get_comments(out SOAPComment[] comments, string api_key, string auth_token, long target_id, string target) {
            return base.Channel.get_comments(out comments, api_key, auth_token, target_id, target);
        }
        
        public string add_comment(out GreenshotBoxPlugin.BoxNet.SOAPComment comment, string api_key, string auth_token, long target_id, string target, string message) {
            return base.Channel.add_comment(out comment, api_key, auth_token, target_id, target, message);
        }
        
        public string delete_comment(string api_key, string auth_token, long target_id) {
            return base.Channel.delete_comment(api_key, auth_token, target_id);
        }
        
        public string search(out SOAPSearchResultItem[] files, out SOAPSearchResultItem[] folders, string api_key, string auth_token, string query, int page, int per_page, string sort, string direction, string[] @params) {
            return base.Channel.search(out files, out folders, api_key, auth_token, query, page, per_page, sort, direction, @params);
        }
        
        public string toggle_folder_email(out string upload_email, string api_key, string auth_token, long folder_id, bool enable) {
            return base.Channel.toggle_folder_email(out upload_email, api_key, auth_token, folder_id, enable);
        }
    }
}
